<?php 
namespace Apps\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class FacebookPostsComments extends ActiveRecord
{
    //your database connection name
    protected $database = 'tutorials';

    // your table name here
    protected $tableName = 'facebook_posts_comments';

    public $primaryKey = 'c_id';

    public function __construct()
    {
        parent::__construct();
    }

}// End of the FacebookPosts Model